---
abstract: 'Portable, standalone (no need for RRDs.pm) tool to create and edit RRD files.'
author:
  - 'Doug Leith <dougleith@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RRD-Editor
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.20'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
